### ISSUE TITLE
Where is the root dir

### ISSUE THREAD

**Issue by kaisar149** [redside100/SauceDetector#1]
`Traceback (most recent call last):
  File "sauce.py", line 3, in <module>
    from SauceOverlay import SauceOverlay
  File "D:\GitClone\SauceDetector\SauceOverlay.py", line 12, in <module>
    import reverse_search
  File "D:\GitClone\SauceDetector\reverse_search.py", line 7, in <module>
    with open('client_id', 'r+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'client_id' `

This is the error I'm getting so I was wondering where you put the client_id

**Comment by kaisar149** [comment]
Figured it out, It's actually the folder with all the scripts
